### ISSUE TITLE
请问如何添加多个DDNS域名

### ISSUE THREAD

**Issue by Goojoe** [zanjie1999/cloudflare-api-v4-ddns#2]
我配置好了ddns,但是我有多个域名需要添加,我不想添加多个脚本所以
1.可以批量添加域名吗?
2.如果有需要怎么做呢?

**Comment by zanjie1999** [comment]
在域名解析设置中添加cname记录就行了，全部指向一个域名，再给那个域名做a记录用这个脚本来更新
