### ISSUE TITLE
关于zone_name和record_name

### ISSUE THREAD

**Issue by qq4199** [zanjie1999/cloudflare-api-v4-ddns#3]
想问一下CFZONE_NAME和CFRECORD_NAME的用法，如果ZONE_NAME是a.com,CFRECORD_NAME每一条解析的都要填么,比如www.a.com或者c.a.com

![image](https://user-images.githubusercontent.com/40818706/159117891-6ec1be0a-59f4-45f8-af4c-1f1695566f30.png)

**Comment by zanjie1999** [comment]
是
